package com.example.captcha.util;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

@Component
public class DB {
    @Value("${database.url}")
    private String url1;
    @Value("${database.username}")
    private String username1;
    @Value("${database.password}")
    private String password1;

    public static Connection connection = null;
    public static Statement statement = null;

    @Bean
    public void createDatabase() throws SQLException {
        connection = DriverManager.getConnection(url1, username1, password1);
        System.out.println("Connection to database is success");
        statement = connection.createStatement();
        try{
            statement.execute("create database 'captcha'" );
            System.out.println("Captcha Database created successfully");
        }
        catch (Exception e){
            System.out.println("Captcha Database is already created");
        }
        try {
            statement.execute("create table users\n" +
                    "(\n" +
                    "    id       bigint generated by default as identity\n" +
                    "        primary key,\n" +
                    "    captcha  varchar(255),\n" +
                    "    password varchar(255),\n" +
                    "    role     varchar(255),\n" +
                    "    username varchar(255)\n" +
                    ");\n" +
                    "\n" +
                    "alter table users\n" +
                    "    owner to postgres;\n" +
                    "\n" );
            System.out.println("Users table is created");

        } catch (Exception e) {
            System.out.println("Users table is already created");
        }

        try {
            statement.execute("INSERT INTO users(id, captcha, password, username, role) " +
                    "values (1, '', '$2a$10$CpLWnPcNdDrzk5GipV7LEeMhYe1OWdePLiF/9XUBiLTN9AWGGF1Bu','admin', 'ROLE_ADMIN')");

            System.out.println("DEFAULT USERNAME: ADMIN  \n DEFAULT PASSWORD: 123");
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Admin is already created");
        }



    }
}
